### ISSUE TITLE
Websocket forwarding not working with Nginx ingress

### ISSUE THREAD

**Issue by mterhar** [mattermost/mattermost-operator#150]
Hi folks,

I've been further tinkering and the websocket can't make a connection from outside my cluster to inside. 

First off, everything works fine when I'm posting messages or connecting bots or whatever. The only thing that is a problem is the websocket. 

<img width="804" alt="image" src="https://user-images.githubusercontent.com/938684/84099361-71c4b100-a9d7-11ea-88a7-a9fe851b6f44.png">

The config has these:

```yaml
apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  name: mattermost
spec:
  image: mattermost/mattermost-enterprise-edition
  size: 100users
  ingressName: matter.p.fqdn.com
  ingressAnnotations:
    kubernetes.io/ingress.class: public
    cert-manager.io/cluster-issuer: "letsencrypt"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Connection "upgrade";
      proxy_set_header Upgrade "websocket";
      proxy_http_version 1.1;
      proxy_read_timeout 61s;
  useIngressTLS: true
  version: 5.19.1
  mattermostLicenseSecret: ""
  database:
    storageSize: 55Gi
  minio:
    storageSize: 100Gi
  elasticSearch:
    host: ""
    username: ""
    password: ""
```

When I check on whether that flowed through from the operator to the ingress, I'm delighted to find: 

```yaml
$ kubectl describe ing mattermost                                                            
Name:             mattermost
Namespace:        default
Address:          10.2.2.210
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
TLS:
  matter-p-fqdn-com-tls-cert terminates matter.p.terharlab.com
Rules:
  Host                    Path  Backends
  ----                    ----  --------
  matter.p.fqdn.com  
                          /   mattermost:8065 (10.233.84.195:8065)
Annotations:              cert-manager.io/cluster-issuer: letsencrypt
                          kubernetes.io/ingress.class: public
                          mattermost.com/last-applied:
                            {"metadata":{"annotations":{"cert-manager.io/cluster-issuer":"letsencrypt","kubernetes.io/ingress.class":"public","nginx.ingress.kubernete...
                          nginx.ingress.kubernetes.io/configuration-snippet:
                            proxy_set_header Connection "upgrade";
                            proxy_set_header Upgrade "websocket";
                            proxy_http_version 1.1;
                            proxy_read_timeout 61s;
                          nginx.ingress.kubernetes.io/proxy-body-size: 1000M
Events:
  Type    Reason          Age                 From                      Message
  ----    ------          ----                ----                      -------
  Normal  AddedOrUpdated  7m3s (x4 over 30h)  nginx-ingress-controller  Configuration for default/mattermost was added or updated
```

But alas, when I check the actual running config on the ingress controller, I says otherwise. 

```
$ kubectl exec -it ingress-pod-30393  -- cat /etc/nginx/conf.d/default-mattermost.conf
# configuration for default/mattermost
upstream default-mattermost-matter.p.fqdn.com-mattermost-8065 {
	zone default-mattermost-matter.p.fqdn.com-mattermost-8065 256k;
	random two least_conn;
	
	server 10.233.84.195:8065 max_fails=1 fail_timeout=10s max_conns=0;
}
server {
	listen 80;
	listen 443 ssl;
	ssl_certificate /etc/nginx/secrets/default-matter-p-fqdn-com-tls-cert;
	ssl_certificate_key /etc/nginx/secrets/default-matter-p-fqdn-com-tls-cert;
	real_ip_header proxy_protocol;
	server_tokens on;
	server_name matter.p.fqdn.com;

	if ($scheme = http) {
		return 301 https://$host:443$request_uri;
	}
	location / {
		proxy_http_version 1.1;

		proxy_connect_timeout 60s;
		proxy_read_timeout 60s;
		proxy_send_timeout 60s;
		client_max_body_size 1m;
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $host;
		proxy_set_header X-Forwarded-Port $server_port;
		proxy_set_header X-Forwarded-Proto $scheme;
		proxy_buffering on;
		
		proxy_pass http://default-mattermost-matter.p.fqdn.com-mattermost-8065;	
	}
}
```

Honestly I expected to see all of those annotations reflected in the configuration. 

When I look at the ingress logs, I see: 

```
10.15.113.47 - - [09/Jun/2020:02:31:35 +0000] "GET /api/v4/websocket HTTP/1.1" 400 192 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15" "-"
10.15.113.47 - - [09/Jun/2020:02:35:44 +0000] "GET /api/v4/websocket HTTP/1.1" 400 192 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15" "-"
10.15.113.47 - - [09/Jun/2020:02:36:35 +0000] "GET /api/v4/websocket HTTP/1.1" 400 192 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.1.1 Safari/605.1.15" "-"
```

And in the mattermost container, I see: 

```
{"level":"error","ts":1591670144.52219,"caller":"api4/websocket.go:28","msg":"websocket connect err.","error":"websocket: the client is not using the websocket protocol: 'upgrade' token not found in 'Connection' header"}
{"level":"error","ts":1591670144.5222652,"caller":"mlog/log.go:174","msg":"Failed to upgrade websocket connection","path":"/api/v4/websocket","request_id":"5u6mx33ib7bh3ksrszdby7autc","ip_addr":"10.15.113.47","user_id":"b8itqkaxwpnr9geee3smx1gbdc","method":"GET","err_where":"connect","http_code":500,"err_details":""}
```
