### ISSUE TITLE
 How to add custom annotations field?

### ISSUE THREAD

**Issue by qiang93** [mattermost/mattermost-operator#174]
values.yaml add metadata.annotations not effect.
```
apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  name: mattermost
  annotations:
    reloader.stakater.com/auto: "true"
```
