### ISSUE TITLE
Adding support for custom CA certificates

### ISSUE THREAD

**Issue by erezo9** [mattermost/mattermost-operator#180]
For assuring that the machine will not get signed by unkown authority if has custom ca certifcates
And using skip ssl verify is not supported on some components (s3, jenkins plugin etc..)

suggesting adding to the cr 
certificates
  secret:
    - secret 1
    - secret 2

and in the mattermost.go 

add something like this - creating one big volume and volume mounts
havent figured out where and how to get secret data exactly
```
	volumes := []corev1.Volume{}
	volumeMounts:= []corev1.VolumeMount{}
	// Mattermost extra secret
	if mattermost.Spec.customCA {
		volumeMount= append(volumeMounts, corev1.VolumeMount{
			MountPath: "/mattermost-license",
			Name:      "mattermost-license",
			ReadOnly:  true,
		})

		volume = append(volumes, corev1.Volume{
			Name: "certificates",
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{
					SecretName: mattermost.Spec.customCA.secret,
				},
			},
		}
	}


	// Mattermost License

	podAnnotations := map[string]string{}
	if len(mattermost.Spec.MattermostLicenseSecret) != 0 {
		envVarGeneral = append(envVarGeneral, corev1.EnvVar{
			Name:  "MM_SERVICESETTINGS_LICENSEFILELOCATION",
			Value: "/mattermost-license/license",
		})

		volumeMount= append(volumeMounts, corev1.VolumeMount{
			MountPath: "/mattermost-license",
			Name:      "mattermost-license",
			ReadOnly:  true,
		})

		volume = append(volumes, corev1.Volume{
			Name: "mattermost-license",
			VolumeSource: corev1.VolumeSource{
				Secret: &corev1.SecretVolumeSource{
					SecretName: mattermost.Spec.MattermostLicenseSecret,
				},
			},
		})
```

this is from my helm chart that I added to my installation
```
  extraVolumes: 
    - name: certificates
      secret:
        secretName: certificates
  extraVolumeMounts: 
    - name: certificates
      mountPath: /etc/ssl/certs/cert1.pem
      subPath: cert1.pem
    - name: certificates
      mountPath: /etc/ssl/certs/cert2.pem
      subPath: cert2.pem
```
