### ISSUE TITLE
Allow custom db check init container image

### ISSUE THREAD

**Issue by mjnagel** [mattermost/mattermost-operator#226]
#### Summary
Currently the DB check hardcodes the image to either a [curl image](https://github.com/mattermost/mattermost-operator/blob/master/pkg/mattermost/database_external.go#L93) or a [postgres 13 image](https://github.com/mattermost/mattermost-operator/blob/master/pkg/mattermost/database_external.go#L104) depending on the DB connection string. It would be great to have the ability to customize the image being used here (for example, specify a different postgres image that has more security hardening or a different version postgres).

#### Possible fixes
Add a value in the mattermost spec that is consumed when creating the deployment and specifying the init container.

Example of what I'm thinking:
```yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
...
spec:
  database:
    external:
      initDbCheck:
        image: mycustompostgres
        tag: 11.2
...
```

**Comment by Szymongib** [comment]
Thanks for reporting the issue.

I think if we provide the ability to override the image I can see people wanting to modify the command also.
If we would like to go with that, maybe we could take the following approach:
```yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
...
spec:
  database:
    readinessCheck:
       initContainers: [Full Containers deffinition here allowing user to override everything (in Go type []v1.Container)]
```

The `readinessCheck` is just random name I came up on the spot and we can think of something better, the point is that it will allow user to customise the check further. 

In case the `readinessCheck` would be provided by the user, the operator would not inject the default init containers.

What do you think about this approach? @mjnagel @gabrieljackson
