### ISSUE TITLE
Configure custom.json for e.g. Plugins using the Operator with a mounted ConfigMap

### ISSUE THREAD

**Issue by silvermind** [mattermost/mattermost-operator#228]
Hi,

Does the new mattermost operator somehow supports the configuration of custom.json ?

> https://docs.mattermost.com/administration/config-settings.html#load-custom-configuration-defaults

I'm looking for a way to configure the welcomebot in a fully ansible managed setup which seems to require edditing the config.json file. Any ideas on how to achieve this using the operator?

A custom volume mount with a ConfigMap may seems the way to go. But I can't get it to work yet:

```
  mattermostEnv:
    - name: MM_CUSTOM_DEFAULTS_PATH
      value: "/mattermost/config/custom-config-map/custom.json"
  volumeMounts:
  - mountPath: "/mattermost/config/custom-config-map"
    name: mattermost-custom-json-config
  volumes:
    - name: mattermost-custom-json-config
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: mattermost-custom-json-config
```
something like this seems promising, but unfortunatelly the mounted user is root..

Are there any plans to add an initContainer Config or  a PodSecurityContext Config to the operator? So I can manually modifiy the mounted file permissions. e.g.:

securityContext:
  fsGroup: 2000
