### ISSUE TITLE
Feature Request: Add mattermostEnv environment variables to init containers

### ISSUE THREAD

**Issue by paddatrapper** [mattermost/mattermost-operator#263]
Add the mattermostEnv environment variables to the Init Contianers. This would allow setting the database username and password from a secret in the form:

```
username: mmuser
password: mmpassword
```

With a database connection string using `$DB_USER` and `$DB_PASSWORD`, with shell expansion to the correct values. This is helpful for setups using a postgres-operator, where the user's password is automatically generated and stored in a secret like above.

**Comment by paddatrapper** [comment]
Adding to that, it would be great if Mattermost interpreted environment variables in the connection string correctly, so that this worked in the mattermost container too.

**Comment by Szymongib** [comment]
Hey @paddatrapper,

I do not think we would like to pass those envs to the Init Containers as they are meant to be specific for Mattermost.

What you can do tho, is to define your own init containers for which you can define your own envs:
```yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mm-example-anywhere
spec:
  ...
  podExtensions:
    initContainers:
      - [YOUR CONTAINER DEFINITION HERE]

```

**Comment by paddatrapper** [comment]
Are those extensions patched in or does it require a full definition of the initContainer?

**Comment by paddatrapper** [comment]
Hmm... It seems this is pointless until mattermost supports interpreting the environment variables within the connection string anyway. Thanks for the guidance!

**Comment by mjnagel** [comment]
@paddatrapper I have done this in the past to override the init container:
```yaml
spec:
  podExtensions:
    initContainers:
      - command:
           - /bin/sh
           - -c
           - until pg_isready --dbname="$DB_CONNECTION_CHECK_URL"; do echo waiting for database; sleep 5; done;
         image: postgres
         name: db-readiness-check
         env:
           - name: DB_CONNECTION_CHECK_URL
              valueFrom:
                secretKeyRef:
                  key: DB_CONNECTION_CHECK_URL
                  name: 'my-db-secret'
  database:
    disableReadinessCheck: true
```

In your case you could reference a secret with the username/password for your DB and change the command to utilize those ENVs. I may have gotten some of the indentation off since I was copying this over from another format inside of a helm chart. Hope this helps...its pretty simple to make a "clone" of the default init container and then modify as you need.
