### ISSUE TITLE
Unable to load configuration: failed to create store (externaldb)

### ISSUE THREAD

**Issue by andrewklau** [mattermost/mattermost-operator#269]
#### Summary
Unable to store external postgres configuration on version 6 and above with read only error

Using this config:

```
  database:
    external:
      secret: mattermost
```

```
kubectl logs -f -n mattermost pod/mattermost-7cc6dbcdfb-9bmd2
Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to write file: open /mattermost/config/postgresql:/user:password@mypostgresdb:25060/defaultdb?sslmode=require: no such file or directory
Usage:
  mattermost [flags]
  mattermost [command]

Available Commands:
  db          Commands related to the database
  export      Export data from Mattermost
  help        Help about any command
  import      Import data.
  jobserver   Start the Mattermost job server
  server      Run the Mattermost server
  version     Display version information

Flags:
  -c, --config string   Configuration file to use.
  -h, --help            help for mattermost

Use "mattermost [command] --help" for more information about a command.

```

#### Steps to reproduce
- Latest mattermost operator
- Deploy mattermost using helm operator and external DB secret

#### Expected behavior
mattermost starts

**Comment by Szymongib** [comment]
Hi @andrewklau,

Could you share your Mattermost CR manifest? I have a hard time understanding what is the problem exactly. Are you just trying to run Mattermost with the external database, or is there something specific to your setup?

It looks like Mattermost is trying to interpret the connection string as a file patch which seems a little weird.

I would appreciate some details so that we can hopefully figure it out.

**Comment by andrewklau** [comment]
Hi @Szymongib 

I'm trying to run mattermost with an external database.  Here's the full yaml file:

```
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mattermost
  namespace: mattermost
spec:
  size: 100users
  ingress:
    enabled: true
    host: chat.example.com
    annotations:
      kubernetes.io/ingress.class: nginx
  version: 6.0.1
  database:
    external:
      secret: mattermost
  fileStore:
    external:
      url: sgp1.digitaloceanspaces.com
      bucket: mymattermost
      secret: mattermost
  mattermostEnv:
  - name: MM_FILESETTINGS_AMAZONS3SSE
    value: "true"
  - name: MM_FILESETTINGS_AMAZONS3SSL
    value: "true"
```

The weird thing is yes it comes up as a file name. When I run the command `kubectl logs -f -n mattermost pod/mattermost-7cc6dbcdfb-9bmd2`  this comes up in the logs:

```
Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to write file: open /mattermost/config/postgresql:/user:password@mypostgresdb:25060/defaultdb?sslmode=require: no such file or directory
Usage:
  mattermost [flags]
  mattermost [command]

Available Commands:
  db          Commands related to the database
  export      Export data from Mattermost
  help        Help about any command
  import      Import data.
  jobserver   Start the Mattermost job server
  server      Run the Mattermost server
  version     Display version information

Flags:
  -c, --config string   Configuration file to use.
  -h, --help            help for mattermost

Use "mattermost [command] --help" for more information about a command.
```

The secret file:

```
apiVersion: v1
kind: Secret
metadata:
  name: mattermost
  namespace: mattermost
type: Opaque
stringData:
  DB_CONNECTION_STRING: 'postgresql://admin:admin@db-mattermost-10088757-0.b.db.example.com:25060/defaultdb?sslmode=require'
```
