### ISSUE TITLE
Mattermost | Ingress TLS | Cert-manager | ClusterIssuer not working

### ISSUE THREAD

**Issue by bitvijays** [mattermost/mattermost-operator#278]
Dear Mattermost Operator Team and the community,

Hope everyone is doing well. Thank you for the awesome work on the Mattermost operator. We really appreciate it; it helps us to make our life easier. Thank you :).

#### Summary

We are trying to deploy Mattermost on a Kubernetes Cluster. Cluster already has cert-manager (cluster-issuer) and Nginx ingress controller. However, when the certificate is issued, it is from `Kubernetes Ingress Controller Fake Certificate` rather than the `cluster-issuer`. We did test if our cluster-issuer is issuing certificates or not, and it does. We are unsure what is wrong or how to debug it; some guidance would be appreciated. Thank you :)

#### Steps to reproduce

- Reproduce the issue using by installing the Mattermost on on-prem Kubernetes with the below 

```yaml
apiVersion: installation.mattermost.com/v1beta1
kind: Mattermost
metadata:
  name: mm-bitvijays                         # Chose the desired name
spec:
  size: 200users                               # Adjust to your requirements
  ingress:
    enabled: true
    host: mattermost.bitvijays.local        # Adjust to your domain
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      cert-manager.io/cluster-issuer: vault-issuer-4
      cert-manager.io/common-name: mattermost.bitvijays.local
  version: 6.0.1
  licenseSecret: ""                             # If you have created secret in step 1, put its name here
```

- Mattermost image is `mattermost/mattermost-operator:v1.18.0`

#### Expected behavior
- Mattermost should have requested the certificate from the `ClusterIssuer` and the clusterissuer issued certificate should be displayed when accessing the mattermost website.

#### Observed behavior (that appears unintentional)

Certificate is issued by the Kubernetes Ingress Controller Fake Certificate rather than by the `ClusterIssuer`

![image](https://user-images.githubusercontent.com/9039339/166987348-f221e256-55e2-4945-985e-31ed7335d3ee.png)

#### Possible fixes

It might be because of the fact that the `kubernetes.io/ingress.class` annotation is deprecated and replaced by the `ingressClassName` parameter in the latest `ingress` spec.

ArgoCD Operator is also probably having the same issue. May refer https://github.com/argoproj-labs/argocd-operator/issues/626
