### ISSUE TITLE
[FEATURE]: Add support for COSI

### ISSUE THREAD

**Issue by shanduur** [mattermost/mattermost-operator#365]
#### Summary

Allow usage of kubernetes controlled `Buckets` and `BucketAccesses` instead of manually provided secrets via Container Object Storage Interface (COSI).

#### Expected behavior

COSI stands for [Container Object Storage Interface](https://container-object-storage-interface.github.io/). It is similar to the CSI spec, but instead of targeting the Block and File storage, it targets the Object storage - e.g. AWS S3, MinIO, Dell EMC ObjectScale and other. It defines few new concepts like `Buckets`, `BucketClaims`, `BucketClasses`, `BucketAccesses` and `BucketAccessClasses`.

- `Buckets` - represents a Bucket (or its equivalent) in the storage backend. Generally, it should be created only in the brownfield provisioning scenario, otherwise is automatically created by controller. Think of [`PersistentVolume` / `PV`](https://kubernetes.io/docs/concepts/storage/persistent-volumes/) but for Object storage.

  Sample manifest:

  ```yaml
  apiVersion: objectstorage.k8s.io/v1alpha1
  kind: Bucket
  metadata:
    name: my-bucket
  spec:
    driverName: cosi.dellemc.com
    bucketClassName: my-bucket-class
    bucketClaim: my-bucket-claim
    deletionPolicy: Delete
    protocols:
      - S3
    parameters:
      param1: value
  ```

- `BucketClaims` - represents a claim (or request) to provision a Bucket. Think of [`PersistentVolumeClaim` / `PVC`](hhttps://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims) but for Object storage.

  Sample manifest:

  ```yaml
  apiVersion: objectstorage.k8s.io/v1alpha1
  kind: BucketClaim
  metadata:
    name: my-bucketclaim
    namespace: my-namespace
  spec:
    bucketClassName: my-bucketclass
    protocols: [ 'S3' ]
  ```

- `BucketClasses` - represents a class of `Bucket` resources with similar characteristics. It should be created by cluster administrator. Think of [`StorageClass` / `SC`](https://kubernetes.io/docs/concepts/storage/storage-classes/) but for Object storage.

  Sample manifest:

  ```yaml
  apiVersion: objectstorage.k8s.io/v1alpha1
  kind: BucketClass
  metadata:
    name: my-bucketclass
  driverName: cosi.dellemc.com
  deletionPolicy: Delete
  parameters:
    param1: value
  ```

- `BucketAccesses` - represents a access request to generate a `Secret`, that will allow you to access Object storage.

  Sample manifest:

  ```yaml
  apiVersion: objectstorage.k8s.io/v1alpha1
  kind: BucketAccess
  metadata:
    name: my-bucketaccess
    namespace: my-namespace
  spec:
    bucketClaimName: my-bucketclaim
    protocol: S3
    bucketAccessClassName: my-bucketaccessclass
    credentialsSecretName: my-s3-secret
  ```

- `BucketAccessClasses` - represents a class of `BucketAccess` resources with similar characteristics. It should be created by cluster administrator.

  Sample manifest:

  ```yaml
  apiVersion: objectstorage.k8s.io/v1alpha1
  kind: BucketAccessClass
  metadata:
    name: my-bucketaccessclass
  driverName: cosi.dellemc.com
  authenticationType: Key
  parameters:
    param1: value
  ```

##### Workflow

![image](https://github.com/mattermost/mattermost-operator/assets/32583062/a9107ddc-7242-4320-aa9f-534ed11f8428)

![image](https://github.com/mattermost/mattermost-operator/assets/32583062/db06ad6b-2f36-4318-8709-db31ba5b8c16)

Right now there are few COSI Drivers that can provision the storage:
- [Azure Blob COSI Driver](https://github.com/Azure/azure-cosi-driver)
- [Ceph COSI](https://github.com/ceph/ceph-cosi)
- [Dell COSI for ObjectScale](https://github.com/dell/cosi)

And few other are under the development, most importantly MinIO.

#### Possible fixes

Until the COSI is in `alpha` (observe [spec](https://github.com/kubernetes-sigs/container-object-storage-interface-spec/releases)) it should stay as optional feature - especially when there is no COSI Driver for AWS and MinIO publicly available.
