### ISSUE TITLE
ingress.spec.ingressClassName is still not implemented

### ISSUE THREAD

**Issue by nullzone** [mattermost/mattermost-operator#383]
#### Summary
It is still not possible to define the ingressClassName parmeter when defining the cluster to be deployed delegating this to using an annotation.

#### Steps to reproduce
Deploy any cluster which has the ingress enabled. The spec.ingressClassName is not defined as there is not a way to register this in the installation manifest.

#### Expected behavior
A parameter should be available in spec.ingress. When defined, the ingress should be created registering in its spec the parameter ingressClassName with the defined value. Not defined if not.

#### Observed behavior (that appears unintentional)
None.

#### Possible fixes
Above-mentioned.
- Register a new parameter/option in the Mattermost manifest / object to define this.
- Use this Parameter only when defined to create the ingress object.

**Comment by gabrieljackson** [comment]
I may not fully understand the issue here, but ingressClassName should already be supported. Is the issue that `ingressClassName` is not set when also using some combination of annotations? Note that `spec.ingress.ingressClass` sets the Class Name value of the ingress.

Here is an example Mattermost v1beta1 ingress snippet I just tested:

```
    ingress:
      ingressClass: nginx-controller
```

And here is the resulting ingress:

```
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  spec:
    ingressClassName: nginx-controller
    rules:
    - host: example.domain
      http:
        paths:
        - backend:
            service:
              name: name
              port:
                number: 8065
          path: /
          pathType: ImplementationSpecific
```

Let me know if I am missing something. Ingress Class name support was added in 2021: https://github.com/mattermost/mattermost-operator/pull/254
