### ISSUE TITLE
Unable to upload picture

### ISSUE THREAD

**Issue by lewandowskim1988** [mattermost/mattermost-operator#399]
## Configuration

I installed `mattermost` on my k8s cluster with usage of [helm chart](https://github.com/mattermost/mattermost-helm).
Below is `values.yaml` configuration:

```
nameOverride: mattermost
fullnameOverride: mattermost
mattermostOperator:
  image:
    tag: v1.22.1
mattermostCR:
  enabled: true
  name: skynet
  spec:
    version: 10.6.1
    database:
      external:
        secret: db-credentials
    fileStore:
      local:
        enabled: true
        storageSize: 10Gi
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      host: mattermost.lewandowskim.com
      ingressClass: nginx
      tlsSecret: tls-wildcard-lewandowskim-com
    replicas: 1
    scheduling:
      resources:
        requests:
          cpu: 500m
          memory: 600Mi
        limits:
          cpu: 600m
          memory: 700Mi
    mattermostEnv:
      - name: MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS
        value: "n8n.lewandowskim.com"
```

## Issue

When I try to upload profile picture I get following error message in desktop app

![Image](https://github.com/user-attachments/assets/fc8e115a-2d71-4c58-8707-4ab12df63d0a)

When I am checking server logs I see error message:
```
{"timestamp":"2025-03-18 15:21:42.774 Z","level":"error","msg":"Couldn't upload profile image.","caller":"web/context.go:123","path":"/api/v4/users/ppa3zirpnigwdxd77fqsaqyraw/image","request_id":"84injr3hzfyx3rw64waoezsi4a","ip_addr":"10.42.0.95","user_id":"ppa3zirpnigwdxd77fqsaqyraw","method":"POST","err_where":"SetProfileImage","http_code":500,"error":"SetProfileImage: Couldn't upload profile image., WriteFile: Unable to write the file., unable to create the directory /mattermost/data/users/ppa3zirpnigwdxd77fqsaqyraw for the file /mattermost/data/users/ppa3zirpnigwdxd77fqsaqyraw/profile.png: mkdir /mattermost/data/users: permission denied"}
{"timestamp":"2025-03-18 15:21:42.774 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:175","method":"POST","url":"/api/v4/users/ppa3zirpnigwdxd77fqsaqyraw/image","request_id":"84injr3hzfyx3rw64waoezsi4a","user_id":"ppa3zirpnigwdxd77fqsaqyraw","status_code":"500"}
{"timestamp":"2025-03-18 15:21:42.890 Z","level":"error","msg":"Unable to write the file.","caller":"web/context.go:123","path":"/api/v4/users/ppa3zirpnigwdxd77fqsaqyraw/image","request_id":"19jinzcgb3rn3ytabp989odhso","ip_addr":"10.42.0.95","user_id":"ppa3zirpnigwdxd77fqsaqyraw","method":"GET","err_where":"WriteFile","http_code":500,"error":"WriteFile: Unable to write the file., unable to create the directory /mattermost/data/users/ppa3zirpnigwdxd77fqsaqyraw for the file /mattermost/data/users/ppa3zirpnigwdxd77fqsaqyraw/profile.png: mkdir /mattermost/data/users: permission denied"}
{"timestamp":"2025-03-18 15:21:42.890 Z","level":"debug","msg":"Received HTTP request","caller":"web/handlers.go:175","method":"GET","url":"/api/v4/users/ppa3zirpnigwdxd77fqsaqyraw/image","request_id":"19jinzcgb3rn3ytabp989odhso","user_id":"ppa3zirpnigwdxd77fqsaqyraw","status_code":"500"}
```

When I checked permissions on mentioned folder they are indeed not right

![Image](https://github.com/user-attachments/assets/e98214c5-741e-4d24-8a05-9ac514d34a03)

Could you help me to resolve this issue?
