### ISSUE TITLE
Mattermost install-kubernetes TLS Ingress Controller

### ISSUE THREAD

**Issue by macevil** [mattermost/mattermost-operator#97]
We have installed Mattermost with the k8s [manual](https://docs.mattermost.com/install/install-kubernetes.html). Successful! :) After that we tried to [configure](https://kubernetes.io/docs/concepts/services-networking/ingress/#tls) a TLS certificate on the Mattermost Ingress Controller, but there is no option in the `mattermost-installation.yaml`.  

``` yaml
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: tls-example-ingress
spec:
  tls:
  - hosts:
    - sslexample.foo.com
    secretName: testsecret-tls
```

Will this feature come or can we solve this differently?

**Comment by cpanato** [comment]
Thanks @macevil checking the code, the TLS is really missing, we can add that.
Are you willing to open a PR to add this missing item? otherwise, I can make it happen.
thanks

**Comment by macevil** [comment]
@cpanato so we try it :)

**Comment by cpanato** [comment]
cool @macevil any questions let me know

**Comment by DustinAlandzes** [comment]
I also got the operator running, with nginx-ingress but want to use HTTPS/SSL/TLS. Do I need to make an Ingress like @macevil has in the first post?

Have been trying to follow this to install cert-manager and use lets encrypt: https://cert-manager.io/docs/tutorials/acme/ingress/

But I still see the Acme Co fake certificate

My `mattermost-installation.yaml` looks like this:
```
apiVersion: mattermost.com/v1alpha1
kind: ClusterInstallation
metadata:
  name: mm-example-full
spec:
  size: 100users
  ingressName: example.20xx.tech
  ingressAnnotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/issuer: "letsencrypt-staging"
  version: 5.14.0
  mattermostLicenseSecret: ""
  database:
    storageSize: 10Gi
  minio:
    storageSize: 10Gi
  elasticSearch:
    host: ""
    username: ""
    password: ""
```

**Comment by macevil** [comment]
Hey @DustinAlandzes,   
your mattermost-installation.yaml is correct, but during Mattermost Operator Installation the Ingress tls spec is not generated yet.

You can take a look in your deployt Mattermost Ingress, this section will be missing and that's the reason why you still getting the Fake Cert.
```
  tls:
  - hosts:
    - chat.domain.dev
    secretName: chat-domain-dev-tls-cert
```

We fixed this with https://github.com/mattermost/mattermost-operator/issues/97
